/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.library_project;

/**
 *
 * @author 201125
 */
public class MainUI extends javax.swing.JFrame {
    private Library library;
    /**
     * Creates new form MainUI
     */
    private Book findBookByTitle(String title) {
    for (Book book : library.getBooks()) {
        if (book.getTitle().equalsIgnoreCase(title)) {
            return book;
        }
    }
    return null;
}

private Student findStudentByName(String name) {
    for (Student student : library.getStudents()) {
        if (student.getName().equalsIgnoreCase(name)) {
            return student;
        }
    }
    return null;
}
    
    public MainUI() {
        initComponents();
        this.setLocationRelativeTo(null);
        ;
        library = new Library();
        Author a1 = new Author(1, "ayman", "dura", "21/7/2002");
        Author a2 = new Author(2, "mohannad", "dura", "21/7/2002");
        Author a3 = new Author(3, "alaa", "dura", "21/7/2002");
        Author a4 = new Author(4, "ahmad", "dura", "21/7/2002");
        Author a5 = new Author(5, "ali", "dura", "21/7/2002");
        library.addAuthor(a1);
        library.addAuthor(a2);
        library.addAuthor(a3);
        library.addAuthor(a4);
        library.addAuthor(a5);
        
        
        
        
    }
     
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        tappedpane = new javax.swing.JTabbedPane();
        addbook_panel = new javax.swing.JPanel();
        author_bookl = new javax.swing.JLabel();
        No_bookl = new javax.swing.JLabel();
        title_bookl = new javax.swing.JLabel();
        genre_bookl = new javax.swing.JLabel();
        version_bookl = new javax.swing.JLabel();
        add_date_bookl = new javax.swing.JLabel();
        title_bookt = new javax.swing.JTextField();
        No_bookt = new javax.swing.JTextField();
        author_bookt = new javax.swing.JTextField();
        genre_bookt = new javax.swing.JTextField();
        version_bookt = new javax.swing.JTextField();
        add_date_bookt = new javax.swing.JTextField();
        add_bookb = new javax.swing.JButton();
        addmagazine_panel = new javax.swing.JPanel();
        title_magazinel = new javax.swing.JLabel();
        title_magazinet = new javax.swing.JTextField();
        No_magazinel = new javax.swing.JLabel();
        No_magazinet = new javax.swing.JTextField();
        author_magazinel = new javax.swing.JLabel();
        author_magazinet = new javax.swing.JTextField();
        genre_magazinet = new javax.swing.JTextField();
        genre_magazinel = new javax.swing.JLabel();
        version_magazinel = new javax.swing.JLabel();
        version_magazinet = new javax.swing.JTextField();
        add_date_magazinet = new javax.swing.JTextField();
        add_date_magazinel = new javax.swing.JLabel();
        release_date_magazinel = new javax.swing.JLabel();
        release_date_magazinet = new javax.swing.JTextField();
        issue_No_magazinel = new javax.swing.JLabel();
        issue_No_magazinet = new javax.swing.JTextField();
        add_magazineb = new javax.swing.JButton();
        addjournal_panel = new javax.swing.JPanel();
        title_journall = new javax.swing.JLabel();
        title_journalt = new javax.swing.JTextField();
        No_journall = new javax.swing.JLabel();
        No_journalt = new javax.swing.JTextField();
        author_journall = new javax.swing.JLabel();
        author_journalt = new javax.swing.JTextField();
        genre_journall = new javax.swing.JLabel();
        genre_journalt = new javax.swing.JTextField();
        version_journall = new javax.swing.JLabel();
        version_journalt = new javax.swing.JTextField();
        add_date_journall = new javax.swing.JLabel();
        add_date_journalt = new javax.swing.JTextField();
        issue_No_journall = new javax.swing.JLabel();
        issue_No_journalt = new javax.swing.JTextField();
        conference_No_journall = new javax.swing.JLabel();
        conference_No_journalt = new javax.swing.JTextField();
        add_journalb = new javax.swing.JButton();
        search_panel = new javax.swing.JPanel();
        title_book_searchl = new javax.swing.JLabel();
        title_book_searcht = new javax.swing.JTextField();
        search_bookb = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        search_resultt = new javax.swing.JTextArea();
        loans_panel = new javax.swing.JPanel();
        title_book_loant = new javax.swing.JTextField();
        title_book_loanl = new javax.swing.JLabel();
        loan_bookb = new javax.swing.JButton();
        name_studentl = new javax.swing.JLabel();
        name_studentt = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        due_date_loant = new javax.swing.JTextArea();
        yeart = new javax.swing.JTextField();
        dayt = new javax.swing.JTextField();
        montht = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        members_panel = new javax.swing.JPanel();
        id_studentl = new javax.swing.JLabel();
        id_studentt = new javax.swing.JTextField();
        name_student_memberl = new javax.swing.JLabel();
        name_student_membert = new javax.swing.JTextField();
        adress_membert = new javax.swing.JTextField();
        adress_memberl = new javax.swing.JLabel();
        birthdatel = new javax.swing.JLabel();
        birthdatet = new javax.swing.JTextField();
        majorl = new javax.swing.JLabel();
        majort = new javax.swing.JTextField();
        add_memberb = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Library Final Project");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("My Library");

        author_bookl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        author_bookl.setText("Author name:");

        No_bookl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        No_bookl.setText("Book No");

        title_bookl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        title_bookl.setText("Title:");

        genre_bookl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        genre_bookl.setText("Genre:");

        version_bookl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        version_bookl.setText("Version:");

        add_date_bookl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add_date_bookl.setText("Adding date:");

        add_bookb.setText("Add");
        add_bookb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_bookbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addbook_panelLayout = new javax.swing.GroupLayout(addbook_panel);
        addbook_panel.setLayout(addbook_panelLayout);
        addbook_panelLayout.setHorizontalGroup(
            addbook_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addbook_panelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(addbook_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(add_date_bookl, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(version_bookl, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(title_bookl, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(No_bookl, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(author_bookl, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(genre_bookl, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addbook_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(title_bookt)
                    .addComponent(No_bookt)
                    .addComponent(author_bookt)
                    .addComponent(genre_bookt)
                    .addComponent(version_bookt)
                    .addComponent(add_date_bookt, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
                .addContainerGap(276, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addbook_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(add_bookb, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        addbook_panelLayout.setVerticalGroup(
            addbook_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addbook_panelLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(addbook_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(title_bookl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(title_bookt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addbook_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(No_bookl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(No_bookt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addbook_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(author_bookl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(author_bookt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addbook_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genre_bookl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(genre_bookt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addbook_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(version_bookl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(version_bookt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addbook_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_date_bookl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add_date_bookt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(add_bookb)
                .addGap(27, 27, 27))
        );

        tappedpane.addTab("Add a book     ", addbook_panel);

        title_magazinel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        title_magazinel.setText("Title:");

        No_magazinel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        No_magazinel.setText("Magazine No:");

        author_magazinel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        author_magazinel.setText("Author name:");

        genre_magazinel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        genre_magazinel.setText("Genre:");

        version_magazinel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        version_magazinel.setText("version:");

        add_date_magazinel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add_date_magazinel.setText("Adding date:");

        release_date_magazinel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        release_date_magazinel.setText("Release date:");

        issue_No_magazinel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        issue_No_magazinel.setText("Issue No");

        add_magazineb.setText("Add");
        add_magazineb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_magazinebActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addmagazine_panelLayout = new javax.swing.GroupLayout(addmagazine_panel);
        addmagazine_panel.setLayout(addmagazine_panelLayout);
        addmagazine_panelLayout.setHorizontalGroup(
            addmagazine_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addmagazine_panelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(addmagazine_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addmagazine_panelLayout.createSequentialGroup()
                        .addComponent(title_magazinel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(title_magazinet, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
                    .addGroup(addmagazine_panelLayout.createSequentialGroup()
                        .addComponent(No_magazinel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(No_magazinet, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
                    .addGroup(addmagazine_panelLayout.createSequentialGroup()
                        .addComponent(author_magazinel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(author_magazinet, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
                    .addGroup(addmagazine_panelLayout.createSequentialGroup()
                        .addComponent(genre_magazinel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(genre_magazinet, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
                    .addGroup(addmagazine_panelLayout.createSequentialGroup()
                        .addComponent(version_magazinel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(version_magazinet, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
                    .addGroup(addmagazine_panelLayout.createSequentialGroup()
                        .addComponent(add_date_magazinel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(add_date_magazinet, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
                    .addGroup(addmagazine_panelLayout.createSequentialGroup()
                        .addComponent(release_date_magazinel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(release_date_magazinet, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
                    .addGroup(addmagazine_panelLayout.createSequentialGroup()
                        .addComponent(issue_No_magazinel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(issue_No_magazinet, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)))
                .addGap(274, 274, 274))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addmagazine_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(add_magazineb, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        addmagazine_panelLayout.setVerticalGroup(
            addmagazine_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addmagazine_panelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(addmagazine_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(title_magazinel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(title_magazinet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addmagazine_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(No_magazinel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(No_magazinet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addmagazine_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(author_magazinel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(author_magazinet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addmagazine_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genre_magazinel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(genre_magazinet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addmagazine_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(version_magazinel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(version_magazinet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addmagazine_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_date_magazinel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add_date_magazinet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addmagazine_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(release_date_magazinel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(release_date_magazinet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addmagazine_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(issue_No_magazinel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(issue_No_magazinet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(add_magazineb)
                .addGap(27, 27, 27))
        );

        tappedpane.addTab("Add a magazine     ", addmagazine_panel);

        title_journall.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        title_journall.setText("Title:");

        No_journall.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        No_journall.setText("Journal No:");

        author_journall.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        author_journall.setText("Author name:");

        genre_journall.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        genre_journall.setText("Genre:");

        version_journall.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        version_journall.setText("Version:");

        add_date_journall.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add_date_journall.setText("Adding date:");

        issue_No_journall.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        issue_No_journall.setText("Issue number:");

        conference_No_journall.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        conference_No_journall.setText("Conference No:");

        add_journalb.setText("Add");
        add_journalb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_journalbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addjournal_panelLayout = new javax.swing.GroupLayout(addjournal_panel);
        addjournal_panel.setLayout(addjournal_panelLayout);
        addjournal_panelLayout.setHorizontalGroup(
            addjournal_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addjournal_panelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(addjournal_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(add_date_journall, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(version_journall, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(title_journall, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(No_journall, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(author_journall, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(genre_journall, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(issue_No_journall, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(conference_No_journall, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addjournal_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(title_journalt)
                    .addComponent(No_journalt)
                    .addComponent(author_journalt)
                    .addComponent(genre_journalt)
                    .addComponent(version_journalt)
                    .addComponent(add_date_journalt, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(issue_No_journalt, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(conference_No_journalt, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(280, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addjournal_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(add_journalb)
                .addGap(29, 29, 29))
        );
        addjournal_panelLayout.setVerticalGroup(
            addjournal_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addjournal_panelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(addjournal_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(title_journall, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(title_journalt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addjournal_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(No_journall, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(No_journalt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addjournal_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(author_journall, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(author_journalt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addjournal_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genre_journall, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(genre_journalt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addjournal_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(version_journall, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(version_journalt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addjournal_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_date_journall, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add_date_journalt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addjournal_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(issue_No_journall, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(issue_No_journalt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addjournal_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(conference_No_journall, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(conference_No_journalt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(add_journalb)
                .addGap(27, 27, 27))
        );

        tappedpane.addTab("Add a journal     ", addjournal_panel);

        title_book_searchl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        title_book_searchl.setText("Book Title:");

        search_bookb.setText("Search");
        search_bookb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_bookbActionPerformed(evt);
            }
        });

        search_resultt.setColumns(20);
        search_resultt.setRows(5);
        jScrollPane1.setViewportView(search_resultt);

        javax.swing.GroupLayout search_panelLayout = new javax.swing.GroupLayout(search_panel);
        search_panel.setLayout(search_panelLayout);
        search_panelLayout.setHorizontalGroup(
            search_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, search_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(search_bookb, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(search_panelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(title_book_searchl, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(title_book_searcht, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                .addGap(278, 278, 278))
            .addGroup(search_panelLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        search_panelLayout.setVerticalGroup(
            search_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(search_panelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(search_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(title_book_searchl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(title_book_searcht, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(search_bookb)
                .addGap(27, 27, 27))
        );

        tappedpane.addTab("Search     ", search_panel);

        title_book_loanl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        title_book_loanl.setText("Book Title:");

        loan_bookb.setText("Loan this book");
        loan_bookb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loan_bookbActionPerformed(evt);
            }
        });

        name_studentl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        name_studentl.setText("Student name:");

        due_date_loant.setColumns(20);
        due_date_loant.setRows(5);
        jScrollPane2.setViewportView(due_date_loant);

        jLabel2.setText("loaning date:");

        javax.swing.GroupLayout loans_panelLayout = new javax.swing.GroupLayout(loans_panel);
        loans_panel.setLayout(loans_panelLayout);
        loans_panelLayout.setHorizontalGroup(
            loans_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loans_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
            .addGroup(loans_panelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(loans_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loans_panelLayout.createSequentialGroup()
                        .addGroup(loans_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(loans_panelLayout.createSequentialGroup()
                                .addGap(204, 204, 204)
                                .addComponent(loan_bookb))
                            .addComponent(jLabel2))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(loans_panelLayout.createSequentialGroup()
                        .addGroup(loans_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, loans_panelLayout.createSequentialGroup()
                                .addComponent(title_book_loanl, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(title_book_loant))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, loans_panelLayout.createSequentialGroup()
                                .addComponent(name_studentl, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(loans_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(name_studentt)
                                    .addGroup(loans_panelLayout.createSequentialGroup()
                                        .addComponent(dayt, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addComponent(montht, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(yeart, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(276, 276, 276))))
        );
        loans_panelLayout.setVerticalGroup(
            loans_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loans_panelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(loans_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(title_book_loanl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(title_book_loant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(loans_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name_studentl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name_studentt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(loans_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yeart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dayt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(montht, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(loan_bookb)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
        );

        tappedpane.addTab("Loans     ", loans_panel);

        id_studentl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        id_studentl.setText("Student ID:");

        name_student_memberl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        name_student_memberl.setText("Student name:");

        adress_memberl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        adress_memberl.setText("Adress:");

        birthdatel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        birthdatel.setText("Birthdate:");

        majorl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        majorl.setText("Major:");

        add_memberb.setText("Add");
        add_memberb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_memberbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout members_panelLayout = new javax.swing.GroupLayout(members_panel);
        members_panel.setLayout(members_panelLayout);
        members_panelLayout.setHorizontalGroup(
            members_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(members_panelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(members_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(members_panelLayout.createSequentialGroup()
                        .addComponent(id_studentl, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(id_studentt, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
                    .addGroup(members_panelLayout.createSequentialGroup()
                        .addComponent(name_student_memberl, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(name_student_membert, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
                    .addGroup(members_panelLayout.createSequentialGroup()
                        .addComponent(adress_memberl, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(adress_membert, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
                    .addGroup(members_panelLayout.createSequentialGroup()
                        .addComponent(birthdatel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(birthdatet, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
                    .addGroup(members_panelLayout.createSequentialGroup()
                        .addComponent(majorl, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(majort, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)))
                .addGap(266, 266, 266))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, members_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(add_memberb)
                .addGap(27, 27, 27))
        );
        members_panelLayout.setVerticalGroup(
            members_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(members_panelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(members_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id_studentl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(id_studentt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(members_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name_student_memberl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name_student_membert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(members_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adress_memberl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adress_membert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(members_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(birthdatel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(birthdatet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(members_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(majorl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(majort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                .addComponent(add_memberb)
                .addGap(25, 25, 25))
        );

        tappedpane.addTab("Members     ", members_panel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tappedpane, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tappedpane, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loan_bookbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loan_bookbActionPerformed
        // TODO add your handling code here:
        int day = Integer.parseInt(dayt.getText());
        int month = Integer.parseInt(montht.getText());
        int year = Integer.parseInt(yeart.getText());

    // Adding 5 days to the value in dayt text field
    int newDay = day + 5;

    // Display the due date in the text area
    due_date_loant.setText("Return the book before " + newDay + " / " + month + " / " + year + "");

    // Replace "Title of the Book" with the actual title from your text field
    String bookTitle = title_book_loant.getText();

    // Find the book by title in the library
    Book foundBook = findBookByTitle(bookTitle);

    // Set the loan value for the found book to true
    if (foundBook != null) {
        foundBook.setOnLoan(true);
    }
    }//GEN-LAST:event_loan_bookbActionPerformed

    private void add_bookbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_bookbActionPerformed
        // TODO add your handling code here:
    String title = title_bookt.getText();
    int bookNo = Integer.parseInt(No_bookt.getText());
    String authorName = author_bookt.getText();
    String genre = genre_bookt.getText();
    int version = Integer.parseInt(version_bookt.getText());
    String addDate = add_date_bookt.getText();

    Author author = library.getAuthorByName(authorName);

    // Create a new Book object
    Book newBook = new Book(title, author, bookNo, genre, version, addDate, false);

    // Add the new book to the library
    library.addBook(newBook);

    // Clear the text fields after adding the book
        title_bookt.setText("");
        No_bookt.setText("");
        author_bookt.setText("");
        genre_bookt.setText("");
        version_bookt.setText("");
        add_date_bookt.setText("");
    }//GEN-LAST:event_add_bookbActionPerformed

    private void add_magazinebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_magazinebActionPerformed
        // TODO add your handling code here:
        String title = title_magazinet.getText();
        int magazineNo = Integer.parseInt(No_magazinet.getText());
        String authorName = author_magazinet.getText();
        String genre = genre_magazinet.getText();
        int version = Integer.parseInt(version_magazinet.getText());
        String addDate = add_date_magazinet.getText();
        String releaseDate = release_date_magazinet.getText();
        int issueNo = Integer.parseInt(issue_No_magazinet.getText());

    // Assuming that you have a method to get an author by name from the library
    Author author = library.getAuthorByName(authorName);

    // Create a new Magazine object
    Magazine newMagazine = new Magazine(title, author, magazineNo, genre, version, addDate, false, issueNo, releaseDate);

    // Add the new magazine to the library
    library.addMagazine(newMagazine);

    // Clear the text fields after adding the magazine
        title_magazinet.setText("");
        No_magazinet.setText("");
        author_magazinet.setText("");
        genre_magazinet.setText("");
        version_magazinet.setText("");
        add_date_magazinet.setText("");
        release_date_magazinet.setText("");
        issue_No_magazinet.setText("");
    }//GEN-LAST:event_add_magazinebActionPerformed

    private void add_journalbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_journalbActionPerformed
        // TODO add your handling code here:
        String title = title_journalt.getText();
        int journalNo = Integer.parseInt(No_journalt.getText());
        String authorName = author_journalt.getText();
        String genre = genre_journalt.getText();
        int version = Integer.parseInt(version_journalt.getText());
        String addDate = add_date_journalt.getText();
        int issueNo = Integer.parseInt(issue_No_journalt.getText());
        int conferenceNo = Integer.parseInt(conference_No_journalt.getText());

        // Assuming that you have a method to get an author by name from the library
        Author author = library.getAuthorByName(authorName);

        // Create a new Journal object
        Journal newJournal = new Journal(title, author, journalNo, genre, version, addDate, false, issueNo, conferenceNo);

        // Add the new journal to the library
        library.addJournal(newJournal);

    // Clear the text fields after adding the journal
        title_journalt.setText("");
        No_journalt.setText("");
        author_journalt.setText("");
        genre_journalt.setText("");
        version_journalt.setText("");
        add_date_journalt.setText("");
        issue_No_journalt.setText("");
        conference_No_journalt.setText("");
    }//GEN-LAST:event_add_journalbActionPerformed

    private void search_bookbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_bookbActionPerformed
        // TODO add your handling code here:
        // Get the title to search
    String searchTitle = title_book_searcht.getText();

    // Perform the search and display the result in the text area
    String searchResult = library.searchByTitle(searchTitle);
    search_resultt.setText(searchResult);
    }//GEN-LAST:event_search_bookbActionPerformed

    private void add_memberbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_memberbActionPerformed
        // TODO add your handling code here:
        int studentId = Integer.parseInt(id_studentt.getText());
        String studentName = name_student_membert.getText();
        String studentAddress = adress_membert.getText();
        String studentBirthDate = birthdatet.getText();
        String studentMajor = majort.getText();

        Student newStudent = new Student(studentId, studentName, studentAddress, studentBirthDate, studentMajor);
        library.addStudent(newStudent);
        search_resultt.setText(newStudent.toString());
        
        
        id_studentt.setText("");
        name_student_membert.setText("");
        adress_membert.setText("");
        birthdatet.setText("");
        majort.setText("");
    }//GEN-LAST:event_add_memberbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainUI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel No_bookl;
    private javax.swing.JTextField No_bookt;
    private javax.swing.JLabel No_journall;
    private javax.swing.JTextField No_journalt;
    private javax.swing.JLabel No_magazinel;
    private javax.swing.JTextField No_magazinet;
    private javax.swing.JButton add_bookb;
    private javax.swing.JLabel add_date_bookl;
    private javax.swing.JTextField add_date_bookt;
    private javax.swing.JLabel add_date_journall;
    private javax.swing.JTextField add_date_journalt;
    private javax.swing.JLabel add_date_magazinel;
    private javax.swing.JTextField add_date_magazinet;
    private javax.swing.JButton add_journalb;
    private javax.swing.JButton add_magazineb;
    private javax.swing.JButton add_memberb;
    private javax.swing.JPanel addbook_panel;
    private javax.swing.JPanel addjournal_panel;
    private javax.swing.JPanel addmagazine_panel;
    private javax.swing.JLabel adress_memberl;
    private javax.swing.JTextField adress_membert;
    private javax.swing.JLabel author_bookl;
    private javax.swing.JTextField author_bookt;
    private javax.swing.JLabel author_journall;
    private javax.swing.JTextField author_journalt;
    private javax.swing.JLabel author_magazinel;
    private javax.swing.JTextField author_magazinet;
    private javax.swing.JLabel birthdatel;
    private javax.swing.JTextField birthdatet;
    private javax.swing.JLabel conference_No_journall;
    private javax.swing.JTextField conference_No_journalt;
    private javax.swing.JTextField dayt;
    private javax.swing.JTextArea due_date_loant;
    private javax.swing.JLabel genre_bookl;
    private javax.swing.JTextField genre_bookt;
    private javax.swing.JLabel genre_journall;
    private javax.swing.JTextField genre_journalt;
    private javax.swing.JLabel genre_magazinel;
    private javax.swing.JTextField genre_magazinet;
    private javax.swing.JLabel id_studentl;
    private javax.swing.JTextField id_studentt;
    private javax.swing.JLabel issue_No_journall;
    private javax.swing.JTextField issue_No_journalt;
    private javax.swing.JLabel issue_No_magazinel;
    private javax.swing.JTextField issue_No_magazinet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton loan_bookb;
    private javax.swing.JPanel loans_panel;
    private javax.swing.JLabel majorl;
    private javax.swing.JTextField majort;
    private javax.swing.JPanel members_panel;
    private javax.swing.JTextField montht;
    private javax.swing.JLabel name_student_memberl;
    private javax.swing.JTextField name_student_membert;
    private javax.swing.JLabel name_studentl;
    private javax.swing.JTextField name_studentt;
    private javax.swing.JLabel release_date_magazinel;
    private javax.swing.JTextField release_date_magazinet;
    private javax.swing.JButton search_bookb;
    private javax.swing.JPanel search_panel;
    private javax.swing.JTextArea search_resultt;
    private javax.swing.JTabbedPane tappedpane;
    private javax.swing.JLabel title_book_loanl;
    private javax.swing.JTextField title_book_loant;
    private javax.swing.JLabel title_book_searchl;
    private javax.swing.JTextField title_book_searcht;
    private javax.swing.JLabel title_bookl;
    private javax.swing.JTextField title_bookt;
    private javax.swing.JLabel title_journall;
    private javax.swing.JTextField title_journalt;
    private javax.swing.JLabel title_magazinel;
    private javax.swing.JTextField title_magazinet;
    private javax.swing.JLabel version_bookl;
    private javax.swing.JTextField version_bookt;
    private javax.swing.JLabel version_journall;
    private javax.swing.JTextField version_journalt;
    private javax.swing.JLabel version_magazinel;
    private javax.swing.JTextField version_magazinet;
    private javax.swing.JTextField yeart;
    // End of variables declaration//GEN-END:variables
}
