/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.library_project;

/**
 *
 * @author 201125
 */
public class MainUI extends javax.swing.JFrame {

    /**
     * Creates new form MainUI
     */
    public MainUI() {
        initComponents();
        this.setLocationRelativeTo(null);
        ;
    }
     
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        tappedpane = new javax.swing.JTabbedPane();
        addbook_panel = new javax.swing.JPanel();
        author_bookl = new javax.swing.JLabel();
        No_bookl = new javax.swing.JLabel();
        title_bookl = new javax.swing.JLabel();
        genre_bookl = new javax.swing.JLabel();
        version_bookl = new javax.swing.JLabel();
        add_date_bookl = new javax.swing.JLabel();
        title_bookt = new javax.swing.JTextField();
        No_bookt = new javax.swing.JTextField();
        author_bookt = new javax.swing.JTextField();
        genre_bookt = new javax.swing.JTextField();
        version_bookt = new javax.swing.JTextField();
        add_date_bookt = new javax.swing.JTextField();
        add_bookb = new javax.swing.JButton();
        addmagazine_panel = new javax.swing.JPanel();
        title_magazinel = new javax.swing.JLabel();
        title_magazinet = new javax.swing.JTextField();
        No_magazinel = new javax.swing.JLabel();
        No_magazinet = new javax.swing.JTextField();
        author_magazinel = new javax.swing.JLabel();
        author_magazinet = new javax.swing.JTextField();
        genre_magazinet = new javax.swing.JTextField();
        genre_magazinel = new javax.swing.JLabel();
        version_magazinel = new javax.swing.JLabel();
        version_magazinet = new javax.swing.JTextField();
        add_date_magazinet = new javax.swing.JTextField();
        add_date_magazinel = new javax.swing.JLabel();
        release_date_magazinel = new javax.swing.JLabel();
        release_date_magazinet = new javax.swing.JTextField();
        issue_No_magazinel = new javax.swing.JLabel();
        issue_No_magazinet = new javax.swing.JTextField();
        add_magazineb = new javax.swing.JButton();
        addjournal_panel = new javax.swing.JPanel();
        title_journall = new javax.swing.JLabel();
        title_journalt = new javax.swing.JTextField();
        No_journall = new javax.swing.JLabel();
        No_journalt = new javax.swing.JTextField();
        author_journall = new javax.swing.JLabel();
        author_journalt = new javax.swing.JTextField();
        genre_journall = new javax.swing.JLabel();
        genre_journalt = new javax.swing.JTextField();
        version_journall = new javax.swing.JLabel();
        version_journalt = new javax.swing.JTextField();
        add_date_journall = new javax.swing.JLabel();
        add_date_journalt = new javax.swing.JTextField();
        issue_No_journall = new javax.swing.JLabel();
        issue_No_journalt = new javax.swing.JTextField();
        conference_No_journall = new javax.swing.JLabel();
        conference_No_journalt = new javax.swing.JTextField();
        add_journalb = new javax.swing.JButton();
        search_panel = new javax.swing.JPanel();
        title_book_searchl = new javax.swing.JLabel();
        title_book_searcht = new javax.swing.JTextField();
        search_bookb = new javax.swing.JButton();
        loans_panel = new javax.swing.JPanel();
        title_book_loant = new javax.swing.JTextField();
        title_book_loanl = new javax.swing.JLabel();
        loan_bookb = new javax.swing.JButton();
        name_studentl = new javax.swing.JLabel();
        name_studentt = new javax.swing.JTextField();
        members_panel = new javax.swing.JPanel();
        id_studentl = new javax.swing.JLabel();
        id_studentt = new javax.swing.JTextField();
        name_student_memberl = new javax.swing.JLabel();
        name_student_membert = new javax.swing.JTextField();
        adress_membert = new javax.swing.JTextField();
        adress_memberl = new javax.swing.JLabel();
        birthdatel = new javax.swing.JLabel();
        birthdatet = new javax.swing.JTextField();
        majorl = new javax.swing.JLabel();
        majort = new javax.swing.JTextField();
        add_memberb = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("My Library");

        author_bookl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        author_bookl.setText("Author name:");

        No_bookl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        No_bookl.setText("Book No");

        title_bookl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        title_bookl.setText("Title:");

        genre_bookl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        genre_bookl.setText("Genre:");

        version_bookl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        version_bookl.setText("Version:");

        add_date_bookl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add_date_bookl.setText("Adding date:");

        add_bookb.setText("Add");
        add_bookb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_bookbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addbook_panelLayout = new javax.swing.GroupLayout(addbook_panel);
        addbook_panel.setLayout(addbook_panelLayout);
        addbook_panelLayout.setHorizontalGroup(
            addbook_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addbook_panelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(addbook_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(add_date_bookl, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(version_bookl, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(title_bookl, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(No_bookl, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(author_bookl, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(genre_bookl, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addbook_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(title_bookt)
                    .addComponent(No_bookt)
                    .addComponent(author_bookt)
                    .addComponent(genre_bookt)
                    .addComponent(version_bookt)
                    .addComponent(add_date_bookt, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
                .addContainerGap(276, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addbook_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(add_bookb, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        addbook_panelLayout.setVerticalGroup(
            addbook_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addbook_panelLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(addbook_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(title_bookl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(title_bookt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addbook_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(No_bookl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(No_bookt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addbook_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(author_bookl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(author_bookt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addbook_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genre_bookl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(genre_bookt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addbook_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(version_bookl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(version_bookt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addbook_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_date_bookl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add_date_bookt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(add_bookb)
                .addGap(27, 27, 27))
        );

        tappedpane.addTab("Add a book     ", addbook_panel);

        title_magazinel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        title_magazinel.setText("Title:");

        No_magazinel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        No_magazinel.setText("Magazine No:");

        author_magazinel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        author_magazinel.setText("Author name:");

        genre_magazinel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        genre_magazinel.setText("Genre:");

        version_magazinel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        version_magazinel.setText("version:");

        add_date_magazinel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add_date_magazinel.setText("Adding date:");

        release_date_magazinel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        release_date_magazinel.setText("Release date:");

        issue_No_magazinel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        issue_No_magazinel.setText("Issue No");

        add_magazineb.setText("Add");

        javax.swing.GroupLayout addmagazine_panelLayout = new javax.swing.GroupLayout(addmagazine_panel);
        addmagazine_panel.setLayout(addmagazine_panelLayout);
        addmagazine_panelLayout.setHorizontalGroup(
            addmagazine_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addmagazine_panelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(addmagazine_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addmagazine_panelLayout.createSequentialGroup()
                        .addComponent(title_magazinel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(title_magazinet, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
                    .addGroup(addmagazine_panelLayout.createSequentialGroup()
                        .addComponent(No_magazinel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(No_magazinet, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
                    .addGroup(addmagazine_panelLayout.createSequentialGroup()
                        .addComponent(author_magazinel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(author_magazinet, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
                    .addGroup(addmagazine_panelLayout.createSequentialGroup()
                        .addComponent(genre_magazinel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(genre_magazinet, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
                    .addGroup(addmagazine_panelLayout.createSequentialGroup()
                        .addComponent(version_magazinel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(version_magazinet, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
                    .addGroup(addmagazine_panelLayout.createSequentialGroup()
                        .addComponent(add_date_magazinel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(add_date_magazinet, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
                    .addGroup(addmagazine_panelLayout.createSequentialGroup()
                        .addComponent(release_date_magazinel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(release_date_magazinet, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
                    .addGroup(addmagazine_panelLayout.createSequentialGroup()
                        .addComponent(issue_No_magazinel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(issue_No_magazinet, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)))
                .addGap(274, 274, 274))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addmagazine_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(add_magazineb, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        addmagazine_panelLayout.setVerticalGroup(
            addmagazine_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addmagazine_panelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(addmagazine_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(title_magazinel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(title_magazinet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addmagazine_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(No_magazinel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(No_magazinet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addmagazine_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(author_magazinel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(author_magazinet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addmagazine_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genre_magazinel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(genre_magazinet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addmagazine_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(version_magazinel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(version_magazinet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addmagazine_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_date_magazinel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add_date_magazinet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addmagazine_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(release_date_magazinel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(release_date_magazinet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addmagazine_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(issue_No_magazinel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(issue_No_magazinet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(add_magazineb)
                .addGap(27, 27, 27))
        );

        tappedpane.addTab("Add a magazine     ", addmagazine_panel);

        title_journall.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        title_journall.setText("Title:");

        No_journall.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        No_journall.setText("Journal No:");

        author_journall.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        author_journall.setText("Author name:");

        genre_journall.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        genre_journall.setText("Genre:");

        version_journall.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        version_journall.setText("Version:");

        add_date_journall.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add_date_journall.setText("Adding date:");

        issue_No_journall.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        issue_No_journall.setText("Issue number:");

        conference_No_journall.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        conference_No_journall.setText("Conference No:");

        add_journalb.setText("Add");

        javax.swing.GroupLayout addjournal_panelLayout = new javax.swing.GroupLayout(addjournal_panel);
        addjournal_panel.setLayout(addjournal_panelLayout);
        addjournal_panelLayout.setHorizontalGroup(
            addjournal_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addjournal_panelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(addjournal_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(add_date_journall, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(version_journall, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(title_journall, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(No_journall, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(author_journall, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(genre_journall, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(issue_No_journall, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(conference_No_journall, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addjournal_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(title_journalt)
                    .addComponent(No_journalt)
                    .addComponent(author_journalt)
                    .addComponent(genre_journalt)
                    .addComponent(version_journalt)
                    .addComponent(add_date_journalt, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(issue_No_journalt, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(conference_No_journalt, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(280, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addjournal_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(add_journalb)
                .addGap(29, 29, 29))
        );
        addjournal_panelLayout.setVerticalGroup(
            addjournal_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addjournal_panelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(addjournal_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(title_journall, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(title_journalt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addjournal_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(No_journall, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(No_journalt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addjournal_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(author_journall, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(author_journalt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addjournal_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genre_journall, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(genre_journalt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addjournal_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(version_journall, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(version_journalt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addjournal_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_date_journall, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add_date_journalt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addjournal_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(issue_No_journall, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(issue_No_journalt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addjournal_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(conference_No_journall, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(conference_No_journalt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(add_journalb)
                .addGap(27, 27, 27))
        );

        tappedpane.addTab("Add a journal     ", addjournal_panel);

        title_book_searchl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        title_book_searchl.setText("Book Title:");

        search_bookb.setText("Search");

        javax.swing.GroupLayout search_panelLayout = new javax.swing.GroupLayout(search_panel);
        search_panel.setLayout(search_panelLayout);
        search_panelLayout.setHorizontalGroup(
            search_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(search_panelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(title_book_searchl, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(title_book_searcht, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                .addGap(278, 278, 278))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, search_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(search_bookb, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        search_panelLayout.setVerticalGroup(
            search_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(search_panelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(search_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(title_book_searchl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(title_book_searcht, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 262, Short.MAX_VALUE)
                .addComponent(search_bookb)
                .addGap(27, 27, 27))
        );

        tappedpane.addTab("Search     ", search_panel);

        title_book_loanl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        title_book_loanl.setText("Book Title:");

        loan_bookb.setText("Loan this book");
        loan_bookb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loan_bookbActionPerformed(evt);
            }
        });

        name_studentl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        name_studentl.setText("Student name:");

        javax.swing.GroupLayout loans_panelLayout = new javax.swing.GroupLayout(loans_panel);
        loans_panel.setLayout(loans_panelLayout);
        loans_panelLayout.setHorizontalGroup(
            loans_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loans_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(loan_bookb)
                .addGap(32, 32, 32))
            .addGroup(loans_panelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(loans_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loans_panelLayout.createSequentialGroup()
                        .addComponent(title_book_loanl, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(title_book_loant, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loans_panelLayout.createSequentialGroup()
                        .addComponent(name_studentl, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(name_studentt, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)))
                .addGap(278, 278, 278))
        );
        loans_panelLayout.setVerticalGroup(
            loans_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loans_panelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(loans_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(title_book_loanl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(title_book_loant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(loans_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name_studentl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name_studentt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 227, Short.MAX_VALUE)
                .addComponent(loan_bookb)
                .addGap(30, 30, 30))
        );

        tappedpane.addTab("Loans     ", loans_panel);

        id_studentl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        id_studentl.setText("Student ID:");

        name_student_memberl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        name_student_memberl.setText("Student name:");

        adress_memberl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        adress_memberl.setText("Adress:");

        birthdatel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        birthdatel.setText("Birthdate:");

        majorl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        majorl.setText("Major:");

        add_memberb.setText("Add");

        javax.swing.GroupLayout members_panelLayout = new javax.swing.GroupLayout(members_panel);
        members_panel.setLayout(members_panelLayout);
        members_panelLayout.setHorizontalGroup(
            members_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(members_panelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(members_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(members_panelLayout.createSequentialGroup()
                        .addComponent(id_studentl, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(id_studentt, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
                    .addGroup(members_panelLayout.createSequentialGroup()
                        .addComponent(name_student_memberl, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(name_student_membert, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
                    .addGroup(members_panelLayout.createSequentialGroup()
                        .addComponent(adress_memberl, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(adress_membert, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
                    .addGroup(members_panelLayout.createSequentialGroup()
                        .addComponent(birthdatel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(birthdatet, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
                    .addGroup(members_panelLayout.createSequentialGroup()
                        .addComponent(majorl, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(majort, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)))
                .addGap(266, 266, 266))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, members_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(add_memberb)
                .addGap(27, 27, 27))
        );
        members_panelLayout.setVerticalGroup(
            members_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(members_panelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(members_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id_studentl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(id_studentt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(members_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name_student_memberl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name_student_membert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(members_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adress_memberl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adress_membert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(members_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(birthdatel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(birthdatet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(members_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(majorl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(majort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                .addComponent(add_memberb)
                .addGap(25, 25, 25))
        );

        tappedpane.addTab("Members     ", members_panel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tappedpane, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tappedpane, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loan_bookbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loan_bookbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loan_bookbActionPerformed

    private void add_bookbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_bookbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_bookbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainUI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel No_bookl;
    private javax.swing.JTextField No_bookt;
    private javax.swing.JLabel No_journall;
    private javax.swing.JTextField No_journalt;
    private javax.swing.JLabel No_magazinel;
    private javax.swing.JTextField No_magazinet;
    private javax.swing.JButton add_bookb;
    private javax.swing.JLabel add_date_bookl;
    private javax.swing.JTextField add_date_bookt;
    private javax.swing.JLabel add_date_journall;
    private javax.swing.JTextField add_date_journalt;
    private javax.swing.JLabel add_date_magazinel;
    private javax.swing.JTextField add_date_magazinet;
    private javax.swing.JButton add_journalb;
    private javax.swing.JButton add_magazineb;
    private javax.swing.JButton add_memberb;
    private javax.swing.JPanel addbook_panel;
    private javax.swing.JPanel addjournal_panel;
    private javax.swing.JPanel addmagazine_panel;
    private javax.swing.JLabel adress_memberl;
    private javax.swing.JTextField adress_membert;
    private javax.swing.JLabel author_bookl;
    private javax.swing.JTextField author_bookt;
    private javax.swing.JLabel author_journall;
    private javax.swing.JTextField author_journalt;
    private javax.swing.JLabel author_magazinel;
    private javax.swing.JTextField author_magazinet;
    private javax.swing.JLabel birthdatel;
    private javax.swing.JTextField birthdatet;
    private javax.swing.JLabel conference_No_journall;
    private javax.swing.JTextField conference_No_journalt;
    private javax.swing.JLabel genre_bookl;
    private javax.swing.JTextField genre_bookt;
    private javax.swing.JLabel genre_journall;
    private javax.swing.JTextField genre_journalt;
    private javax.swing.JLabel genre_magazinel;
    private javax.swing.JTextField genre_magazinet;
    private javax.swing.JLabel id_studentl;
    private javax.swing.JTextField id_studentt;
    private javax.swing.JLabel issue_No_journall;
    private javax.swing.JTextField issue_No_journalt;
    private javax.swing.JLabel issue_No_magazinel;
    private javax.swing.JTextField issue_No_magazinet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JButton loan_bookb;
    private javax.swing.JPanel loans_panel;
    private javax.swing.JLabel majorl;
    private javax.swing.JTextField majort;
    private javax.swing.JPanel members_panel;
    private javax.swing.JLabel name_student_memberl;
    private javax.swing.JTextField name_student_membert;
    private javax.swing.JLabel name_studentl;
    private javax.swing.JTextField name_studentt;
    private javax.swing.JLabel release_date_magazinel;
    private javax.swing.JTextField release_date_magazinet;
    private javax.swing.JButton search_bookb;
    private javax.swing.JPanel search_panel;
    private javax.swing.JTabbedPane tappedpane;
    private javax.swing.JLabel title_book_loanl;
    private javax.swing.JTextField title_book_loant;
    private javax.swing.JLabel title_book_searchl;
    private javax.swing.JTextField title_book_searcht;
    private javax.swing.JLabel title_bookl;
    private javax.swing.JTextField title_bookt;
    private javax.swing.JLabel title_journall;
    private javax.swing.JTextField title_journalt;
    private javax.swing.JLabel title_magazinel;
    private javax.swing.JTextField title_magazinet;
    private javax.swing.JLabel version_bookl;
    private javax.swing.JTextField version_bookt;
    private javax.swing.JLabel version_journall;
    private javax.swing.JTextField version_journalt;
    private javax.swing.JLabel version_magazinel;
    private javax.swing.JTextField version_magazinet;
    // End of variables declaration//GEN-END:variables
}
